### ISSUE TITLE
coremark make compile error ?

### ISSUE THREAD

**Issue by dzwduan** [SpinalHDL/NaxSoftware#1]
ext/NaxSoftware/baremetal/coremark  make compile, get error like this:

../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/cc8Pzv1O.o: in function `.L204':
../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/ccG7LwMN.o: in function `fcvtbuf':
cvt.c:(.text+0x1dac): undefined reference to `__nedf2'
../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/ccG7LwMN.o: in function `fcvt':
cvt.c:(.text+0x14a4): undefined reference to `__ltdf2'

**Comment by Dolu1990** [comment]
Hi,

make rv32ima for instance should work
